components:
  document_cleaner:
    init_parameters:
      remove_empty_lines: true
      remove_extra_whitespaces: true
      remove_regex: null
      remove_repeated_substrings: false
      remove_substrings: null
    type: haystack.components.preprocessors.document_cleaner.DocumentCleaner
  document_embedder:
    init_parameters:
      batch_size: 32
      device:
        device: cpu
        type: single
      embedding_separator: '

        '
      meta_fields_to_embed: []
      model: mixedbread-ai/mxbai-embed-large-v1
      normalize_embeddings: false
      prefix: ''
      progress_bar: true
      suffix: ''
      token:
        env_vars:
        - HF_API_TOKEN
        strict: false
        type: env_var
    type: haystack.components.embedders.sentence_transformers_document_embedder.SentenceTransformersDocumentEmbedder
  document_joiner:
    init_parameters:
      join_mode: concatenate
      sort_by_score: true
      top_k: null
      weights: null
    type: haystack.components.joiners.document_joiner.DocumentJoiner
  document_splitter:
    init_parameters:
      split_by: word
      split_length: 150
      split_overlap: 50
    type: haystack.components.preprocessors.document_splitter.DocumentSplitter
  document_writer:
    init_parameters:
      document_store:
        init_parameters:
          embedding_dim: 1024
          hosts: http://opensearch:9200/
          index: default
          use_ssl: false
          verify_certs: false
        type: haystack_integrations.document_stores.opensearch.document_store.OpenSearchDocumentStore
      policy: NONE
    type: haystack.components.writers.document_writer.DocumentWriter
  file_type_router:
    init_parameters:
      mime_types:
      - text/plain
      - application/pdf
      - text/markdown
    type: haystack.components.routers.file_type_router.FileTypeRouter
  markdown_converter:
    init_parameters:
      progress_bar: true
      table_to_single_line: false
    type: haystack.components.converters.markdown.MarkdownToDocument
  pypdf_converter:
    init_parameters:
      converter_name: default
    type: haystack.components.converters.pypdf.PyPDFToDocument
  text_file_converter:
    init_parameters:
      encoding: utf-8
    type: haystack.components.converters.txt.TextFileToDocument
connections:
- receiver: text_file_converter.sources
  sender: file_type_router.text/plain
- receiver: pypdf_converter.sources
  sender: file_type_router.application/pdf
- receiver: markdown_converter.sources
  sender: file_type_router.text/markdown
- receiver: document_joiner.documents
  sender: text_file_converter.documents
- receiver: document_joiner.documents
  sender: markdown_converter.documents
- receiver: document_joiner.documents
  sender: pypdf_converter.documents
- receiver: document_cleaner.documents
  sender: document_joiner.documents
- receiver: document_splitter.documents
  sender: document_cleaner.documents
- receiver: document_embedder.documents
  sender: document_splitter.documents
- receiver: document_writer.documents
  sender: document_embedder.documents
max_loops_allowed: 100
metadata: {}
