components:
  embedder:
    init_parameters:
      batch_size: 32
      device:
        device: cpu
        type: single
      model: mixedbread-ai/mxbai-embed-large-v1
      normalize_embeddings: false
      prefix: ''
      progress_bar: true
      suffix: ''
      token:
        env_vars:
        - HF_API_TOKEN
        strict: false
        type: env_var
    type: haystack.components.embedders.sentence_transformers_text_embedder.SentenceTransformersTextEmbedder
  llm:
    init_parameters:
      generation_kwargs:
        max_new_tokens: 512
        stop_sequences: []
      model: mistralai/Mistral-7B-Instruct-v0.2
      streaming_callback: null
      token:
        env_vars:
        - HF_API_TOKEN
        strict: false
        type: env_var
      url: null
    type: haystack.components.generators.hugging_face_tgi.HuggingFaceTGIGenerator
  prompt_builder:
    init_parameters:
      template: "\nAnswer the questions based on the given context.\n\nContext:\n\
        {% for document in documents %}\n    {{ document.content }}\n{% endfor %}\n\
        \nQuestion: {{ question }}\nAnswer:\n"
    type: haystack.components.builders.prompt_builder.PromptBuilder
  retriever:
    init_parameters:
      document_store:
        init_parameters:
          hosts: http://opensearch:9200/
          index: default
          use_ssl: false
          verify_certs: false
          embedding_dim: 1024
        type: haystack_integrations.document_stores.opensearch.document_store.OpenSearchDocumentStore
      filters: {}
      top_k: 10
    type: haystack_integrations.components.retrievers.opensearch.embedding_retriever.OpenSearchEmbeddingRetriever
connections:
- receiver: retriever.query_embedding
  sender: embedder.embedding
- receiver: prompt_builder.documents
  sender: retriever.documents
- receiver: llm.prompt
  sender: prompt_builder.prompt
max_loops_allowed: 100
metadata: {}
