components:
  embedder:
    init_parameters:
      batch_size: 32
      device:
        device: cpu
        type: single
      model: google-bert/bert-base-uncased
      normalize_embeddings: false
      prefix: ''
      progress_bar: true
      suffix: ''
      token:
        env_vars:
        - HF_API_TOKEN
        strict: false
        type: env_var
    type: haystack.components.embedders.sentence_transformers_text_embedder.SentenceTransformersTextEmbedder
  llm:
    init_parameters:
      api_base_url: null
      api_key:
        env_vars:
          - OPENAI_API_KEY
        strict: true
        type: env_var
      generation_kwargs: { }
      model: gpt-3.5-turbo
      streaming_callback: null
      system_prompt: null
    type: haystack.components.generators.openai.OpenAIGenerator
  prompt_builder:
    init_parameters:
      template: "\nGiven these documents, answer the question.\nDocuments:\n{% for\
        \ doc in documents %}\n    {{ doc.content }}\n{% endfor %}\nQuestion: {{question}}\n\
        Answer:\n"
    type: haystack.components.builders.prompt_builder.PromptBuilder
  retriever:
    init_parameters:
      document_store:
        init_parameters:
          hosts: http://opensearch:9200/
          index: default
          use_ssl: false
          verify_certs: false
        type: haystack_integrations.document_stores.opensearch.document_store.OpenSearchDocumentStore
      filters: {}
      top_k: 10
    type: haystack_integrations.components.retrievers.opensearch.embedding_retriever.OpenSearchEmbeddingRetriever
connections:
- receiver: retriever.query_embedding
  sender: embedder.embedding
- receiver: prompt_builder.documents
  sender: retriever.documents
- receiver: llm.prompt
  sender: prompt_builder.prompt
max_loops_allowed: 100
data: {}